# Generated by Django 2.0.2 on 2018-02-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('1', 'Em andamento'), ('2', 'Finalizado')], default='1', max_length=1),
        ),
    ]
