# Generated by Django 2.0.4 on 2018-04-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180329_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='professional_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='accounts.ServiceProviderProfile'),
        ),
    ]
