# Generated by Django 2.0.4 on 2018-04-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180415_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='professional_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.UserModel'),
        ),
    ]
