# Generated by Django 2.0.7 on 2018-08-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180415_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregister',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_registers', to='accounts.UserModel'),
        ),
        migrations.AlterField(
            model_name='serviceregister',
            name='status',
            field=models.CharField(choices=[('1', 'Aguardando confirmação'), ('2', 'Em andamento'), ('3', 'Finalizado')], default='1', max_length=1),
        ),
    ]
