# Generated by Django 2.0.2 on 2018-03-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180220_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
